name: Upload Python Package
env:
  APPLICATION_NAME: "My Flask app"
  DEPLOY_VERSION: "ver-${{ github.sha }}"


on:
  push:
    branches: [main, master]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Hello msg
      run: echo "Hello from SRC"

    - name: Show version
      run: echo "Current version: ${{ DEPLOY_VERSION }}"
