name: Check-My-Python-App
env:
  APPLICATION_NAME: "My Flask app"
  DEPLOY_VERSION: "ver-${{ github.sha }}"


on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: test run ...
      run: echo "test success!"

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Hello msg
      run: echo "Hello from SRC"

    - name: Show version
      run: echo "Current version ${{ env.DEPLOY_VERSION }}"

    - name: LS
      run: ls -lah
